version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend/iot_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/iot_frontend:/app
      - /app/node_modules
