version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
    restart: always
    command: >
      sh -c "
      until mysqladmin ping -h db -umyuser -pmypassword --silent; do
        echo 'Waiting for MySQL...'; sleep 2;
      done;
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    build: ./frontend/iot_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/iot_frontend:/app
      - /app/node_modules
    restart: always

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
  
  postdata:
    image: curlimages/curl:8.8.0
    depends_on:
      - backend
    entrypoint: >
      sh -c "
        sleep 5 &&
        curl -X POST http://host.docker.internal:8000/project/sensorDataDisplay/
        -H 'Content-Type: application/json'
        -d '{\"temp\":25, \"ph\":7.5, \"tds\":250, \"waterLv\":95}'
      "

volumes:
  mysql_data:
